method: grid  # or 'random', 'bayes'
name:   BSplines_feat

parameters:
  result_path:
    value:    /u/home/koeglf/Documents/code/registrationbaselines/tmp/results_wandb
  encoder:
    values:   [no_encoder] #DINOv2, SAM, MedSAM]
  metric:
    values:   [{MSE: 0.5, NCC: 0.5}, {MSE: 1.0}, {NCC: 1.0}]
  lr:
    values:   [0.0005]
  regularisation_weight:
    values:   [0, 200, 100000]
  iterations:
    values:   [1000]
  sigma:
    values:   [[2, 2], [6, 6], [20, 20]]