method: grid
name: DemonsSITK

parameters:
  result_path: 
    values:            [/home/fryderyk/Documents/code/registrationbaselines/tmp/displacement_debug]

  filter_type:
    values:               [FastSymmetricForcesDemonsRegistrationFilter]
                          #  SymmetricForcesDemonsRegistrationFilter,
                          #  DiffeomorphicDemonsRegistrationFilter,
                          #  DemonsRegistrationFilter]

  # matcher
  histogram_levels_int8:  
    values:               [128]
  histogram_levels_float: 
    values:               [1024]
  number_of_match_points: 
    values:               [7]

  # demons
  number_of_iterations:   
    values:               [100]
  standard_deviations:    
    values:               [1.0]

  # resampler
  interpolator:           
    values:               [sitkHammingWindowedSinc]
  default_pixel_value:    
    values:               [0]
