method_name: SyNANTs
result_path: /home/anna/tmp/results/
#result_path: /home/fryderyk/Documents/data/results/

grad_step: 0.2 # 0.2
flow_sigma: 3 #3 smoothing of incremental update field
total_sigma: 0 # 0 smoothing of combined field