method_name: SyNANTs

parameters:
  result_path:
#    value:            /u/home/koeglf/Documents/code/registrationbaselines/tmp/exp
    value: /home/anna/PycharmProjects/registrationbaselines/tmp/results/
#result_path: /home/fryderyk/Documents/data/results/

grad_step: 0.2 # 0.2
flow_sigma: 3 #3 smoothing of incremental update field
total_sigma: 0 # 0 smoothing of combined field