# Voxelmorph training configuration, taking all default parameters from original repo

result_model_path: null
initial_weights_path : null
batch_size: 1
epochs: 1
steps_per_epoch: 100
load_model: null
initial_epoch: 0
lr: 0.0001
int_steps: 7
int_downsize: 2
enc:  [16, 32, 32, 32]
dec:  [32, 32, 32, 32, 32, 16, 16]
bidir: False
sim_loss: "mse"
reg_weight: 0.01
use_wandb: False
wandb_config_path: null
gpu:  '0'
save_checkpoint : 20