# Voxelmorph training configuration, taking all default parameters from original repo

# General training args
result_model_path: "tmp/test_lapirn"
initial_weights_path: "tmp/test_lapirn/_w.pt"
batch_size: 1
epochs: 3
steps_per_epoch: 3
load_model: null
initial_epoch: 0
lr: 0.0001

#LapIRN specific args
iteration_lvl1: 30 #30001
iteration_lvl2: 30 #30001
iteration_lvl3: 60 #60001
antifold_weight: 0. # between 0 and 1000
smooth_weight: 1.0 # between 0.1 and 10. 1 (disp), 3.5 (diff)
start_channel: 7
freeze_step: 2000
range_flow: 0.4
use_diff_version: True #False

# wandb and torch args
use_wandb: True
wandb_config_path: "registrationbaselines/configs/Wandb.yaml"
gpu: '0' # -1 if cpu
cudnn_nondet: False
save_checkpoint: 20
model_name: test_model


# inference params
inference_model_path: "tmp/test_lapirn/test_modelstagelvl3_final.pth"
result_path: "tmp/test_lapirn"