# Voxelmorph training configuration, taking all default parameters from original repo

result_model_path: "registrationbaselines/tmp/test"
initial_weights_path : "registrationbaselines/tmp/test/_w.pt"
batch_size: 5 #1
epochs: 3 #1
steps_per_epoch: 3 #100
load_model: null #null
initial_epoch: 0 #0
lr: 0.0001 #0.0001
int_steps: 7 #7
int_downsize: 2 #2
enc:  [16, 32, 32, 32] # [16, 32, 32, 32]
dec:  [32, 32, 32, 32, 32, 16, 16] #[32, 32, 32, 32, 32, 16, 16]
bidir: False # False
sim_loss: "mse" #'mse'
reg_weight: 0.01 #0.01
use_wandb: True
wandb_config_path: "registrationbaselines/configs/Wandb.yaml"
gpu:  '0'
cudnn_nondet: False #False
save_checkpoint : 20 #20


