method: grid
name: VoxelMorph
parameters:
  result_path:
    values:     [/home/koeglf/data/preprocess_again/temp]
  gpu_number:
    values:     [["0,1,2"]]
  multichannel:
    values:     [False]
  batch_size:
    values:     [3]
  epochs:
    values:     [5000]
  steps_per_epoch:
    values:     [3]
  load_model:
    values:     [null]
  initial_epoch:
    values:     [0]
  lr:
    values:     [0.0001, 0.0005, 0.001]
  int_steps:
    values:     [7]
  int_downsize:
    values:     [2]
  enc:
    values:     [[16, 32, 32, 32]]
  dec:
    values:     [[32, 32, 32, 32, 32, 16, 16]]
  bidir:
    values:     [False]
  sim_loss:
    values:     ["mse"]
  reg_weight:
    values:     [0.0]
    # values:     [0.01]
  gpu:
    values:     ['2']
    # values:     ['0,1,2']
  cudnn_nondet:
    values:     [False]
  save_checkpoint:
    values:     [20]