method: grid
name: VoxelMorph
parameters:
  result_path:
    values:     [/u/home/koeglf/Documents/code/registrationbaselines/tmp/exp]
  model_path:
    values:     ["/u/home/koeglf/Documents/code/registrationbaselines/tmp/exp/VoxelMorph/0001_final.pt"]
  gpu_number:
    values:     ["0"]
  multichannel:
    values:     [False]
  result_model_path:
    values:     ["/u/home/koeglf/Documents/code/registrationbaselines/tmp/exp/VoxelMorph"]
  initial_weights_path:
    values:     ["tmp/_w.pt"]
  batch_size:
    values:     [1]
  epochs:
    values:     [1]
  steps_per_epoch:
    values:     [3]
  load_model:
    values:     [null]
  initial_epoch:
    values:     [0]
  lr:
    values:     [0.0001]
  int_steps:
    values:     [7]
  int_downsize:
    values:     [2]
  enc:
    values:     [[16, 32, 32, 32]]
  dec:
    values:     [[32, 32, 32, 32, 32, 16, 16]]
  bidir:
    values:     [False]
  sim_loss:
    values:     ["mse"]
  reg_weight:
    values:     [0.01]
  use_wandb:
    values:     [False]
  wandb_config_path:
    values:     ["registrationbaselines/configs/Wandb.yaml"]
  gpu:
    values:     ['0']
  cudnn_nondet:
    values:     [False]
  save_checkpoint:
    values:     [20]