method_name: VoxelMorphDINOv2-variant1-MI
encoder: SAM
feature_metric: COSINE # MI, MSE
loss_function_variant: 1
feature_reg_weight: 0.5

result_path: /home/anna/PycharmProjects/registrationbaselines/tmp/results

model_path: "/home/anna/PycharmProjects/registrationbaselines/tmp/VoxelMorph/results/0001_final.pt"
gpu_number: "0"
multichannel: False

# Voxelmorph training configuration, taking all default parameters from original repo
result_model_path: "tmp/results/VoxelMorph"
initial_weights_path : "tmp/_w.pt"
batch_size: 32 #1
epochs: 200 #1
steps_per_epoch: 3 #100
load_model: null #null
initial_epoch: 0 #0
lr: 0.0001 #0.0001
int_steps: 7 #7
int_downsize: 1 #2
enc:  [16, 32, 32, 32] # [16, 32, 32, 32]
dec:  [32, 32, 32, 32, 32, 16, 16] #[32, 32, 32, 32, 32, 16, 16]
bidir: False # False
src_feats: 3 #1
trg_feats: 3 #1
sim_loss: "ncc" #'mse'
reg_weight: 0.01 #0.01
use_wandb: True
wandb_config_path: "registrationbaselines/configs/Wandb.yaml"
gpu:  '0'
cudnn_nondet: False #False
save_checkpoint : 20 #20


